# Generated by Django 4.2.16 on 2026-09-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-box-seam', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(db_index=True, max_length=200)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retailer', models.CharField(max_length=200)),
                ('purchase_city', models.CharField(blank=True, max_length=100)),
                ('warranty_duration_months', models.PositiveIntegerField(default=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, help_text='Set if a service center employee registered on behalf of customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
