[phases.setup]
nixPkgs = [
  "tesseract",
  "python311",
  "gcc",
  "file",
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt",
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput",
  "/opt/venv/bin/python manage.py migrate --noinput",
]

[start]
cmd = "/opt/venv/bin/gunicorn assurex.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
