# Generated by Django 4.2.16 on 2026-09-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('standard_duration_months', models.PositiveIntegerField(default=12)),
                ('extended_duration_months', models.PositiveIntegerField(default=0)),
                ('claim_reporting_period_days', models.PositiveIntegerField(default=14, help_text='Max days after fault to report claim')),
                ('covered_faults', models.JSONField(default=list, help_text='List of covered fault types')),
                ('exclusions', models.JSONField(default=list, help_text='List of excluded fault types / conditions')),
                ('mandatory_documents', models.JSONField(default=list, help_text='List of required document types')),
                ('authorized_repair_required', models.BooleanField(default=True)),
                ('max_repair_count', models.PositiveIntegerField(default=2, help_text='Max prior repairs before claim invalid')),
                ('replacement_allowed', models.BooleanField(default=False)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('hard_fail_rules', models.JSONField(default=list)),
                ('warning_rules', models.JSONField(default=list)),
                ('manual_review_rules', models.JSONField(default=list)),
                ('policy_file', models.CharField(blank=True, help_text='Source JSON/YAML policy filename', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_policies', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Warranty Policy',
                'verbose_name_plural': 'Warranty Policies',
                'db_table': 'warranty_policies',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('warranty_type', models.CharField(choices=[('standard', 'Standard'), ('extended', 'Extended'), ('third_party', 'Third Party')], default='standard', max_length=20)),
                ('warranty_provider', models.CharField(default='Manufacturer', max_length=200)),
                ('service_center', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('coverage_description', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('expiring', 'Expiring Soon'), ('extended', 'Extended'), ('void', 'Void')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('warranty_card', models.FileField(blank=True, null=True, upload_to='warranty_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='warranties.warrantypolicy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='products.product')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'db_table': 'warranties',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('hard_fail', 'Hard Fail'), ('warning', 'Warning'), ('manual_review', 'Manual Review')], max_length=20)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('skip', 'Skipped')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='claims.claim')),
            ],
            options={
                'db_table': 'rule_results',
                'ordering': ['rule_name'],
            },
        ),
    ]
