# Generated by Django 4.2.16 on 2026-09-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('warranty_expiry', 'Warranty Expiry Alert'), ('claim_submitted', 'Claim Submitted'), ('claim_status', 'Claim Status Changed'), ('missing_docs', 'Missing Documents'), ('additional_info', 'Additional Info Requested'), ('review_complete', 'Review Completed'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('duplicate_alert', 'Duplicate Claim Alert'), ('model_failure', 'Model Failure'), ('anomaly', 'Anomaly Detected'), ('system', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
